### ISSUE TITLE
Crash when zooming images

### ISSUE THREAD

**Issue by saket** [tom5079/Minamo#21]
I see this crash very often when I'm zooming images. Any ideas why might this be happening?

```
java.lang.IllegalStateException: Offset is unspecified
    at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:67)
    at androidx.compose.ui.geometry.Offset.times-tuRUvjQ(Offset.kt:188)
    at xyz.quaver.graphics.subsampledimage.SubSampledImageKt$SubSampledImage$onFling$1$1.invoke(SubSampledImage.kt:186)
    at xyz.quaver.graphics.subsampledimage.SubSampledImageKt$SubSampledImage$onFling$1$1.invoke(SubSampledImage.kt:181)
    at androidx.compose.animation.core.SuspendAnimationKt.doAnimationFrame(SuspendAnimation.kt:321)
    at androidx.compose.animation.core.SuspendAnimationKt.access$doAnimationFrame(SuspendAnimation.kt:1)
    at androidx.compose.animation.core.SuspendAnimationKt$animate$6.invoke(SuspendAnimation.kt:241)
    at androidx.compose.animation.core.SuspendAnimationKt$animate$6.invoke(SuspendAnimation.kt:229)
...
```

**Comment by tom5079** [comment]
I think it happens when `flingDistance` is 0.
https://github.com/tom5079/SubSampledImage/blob/d6ae2b56251e357c2a9ba773eb39bc4bde0fee56/library/src/main/java/xyz/quaver/graphics/subsampledimage/SubSampledImage.kt#L177
I will publish a fix in a few hours.
Thank you for the report.
