### ISSUE TITLE
Crash when loading this large image

### ISSUE THREAD

**Issue by saket** [tom5079/Minamo#22]
I'm able to load most large images except for this one that's causing `SubSampledImage` to crash on my device: https://i.imgur.com/5OWRScJ.jpg

```
java.lang.RuntimeException: Canvas: trying to draw too large(127126040bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:271)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-9jGpkUE(CanvasDrawScope.kt:239)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-9jGpkUE(Unknown Source:38)
	at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-9jGpkUE$default(DrawScope.kt:472)
	at androidx.compose.ui.graphics.drawscope.DrawScope$DefaultImpls.drawImage-9jGpkUE$default(DrawScope.kt:472)
	at xyz.quaver.graphics.subsampledimage.SubSampledImageKt$SubSampledImage$9.invoke(SubSampledImage.kt:241)
	at xyz.quaver.graphics.subsampledimage.SubSampledImageKt$SubSampledImage$9.invoke(SubSampledImage.kt:192)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
```

**Comment by tom5079** [comment]
I was able to load the image just fine. What is the dimension of the composable and can you provide a code snippet?
Thank you.

![image](https://user-images.githubusercontent.com/7948651/180892219-2334b6cb-acc8-4662-a7df-ab444be5aa15.png)

**Comment by saket** [comment]
So weird. I'm using a Pixel 5 emulator that's running Android API 32. The available space for the image is `1080px x 1862px`.  My code is straightforward:

```kotlin
val imageLoader: coil.ImageLoader = …
imageLoader.execute(
  ImageRequest.Builder(context)
    .data("https://i.imgur.com/5OWRScJ.jpg")
    .build()
)

val diskCache = imageLoader.diskCache
val snapshot = diskCache[url.toString()]!!
val imageSource = diskCache.fileSystem.source(snapshot.data).buffer()
```
```kotlin
SubSampledImage(
  state = rememberSubSampledImageState(),
  modifier = Modifier.matchParentSize(),
  imageSource = rememberInputStreamImageSource(imageSource.inputStream()),
)
```

**Comment by tom5079** [comment]
I figured `Modifier.fillMaxSize()` is the problem. You're trying to create a canvas that is too huge.  

Loding it this way will solve your problem:
```kotlin
val state = rememberSubSampledImageState()
SubSampledImage(
    state = state,
    modifier = Modifier
        .fillMaxWidth()
        .wrapContent(state),
    imageSource = imageSource
)
```

**Comment by saket** [comment]
I need to set a specific set of constraints to my image so wrapping isn't desirable. I think you're assuming that this library is only used as a fullscreen viewer, which may not always be the case.

**Comment by saket** [comment]
FWIW this library does not crash for smaller images for the same canvas size.

**Comment by tom5079** [comment]
try version `0.0.1-alpha22-SNAPSHOT`
